updated telephone link
lokal-ninja/ln-base pull request #18
Opened 2020-10-01 04:51 UTC by ReyhanSara

2020-10-05 09:23 UTC, midzer requested changes
Thanks for your PR!

Have a look at my comments :)

2020-10-05 09:23 UTC, midzer commented on layouts/_default/single.html
> +        {{ with $location.phone }}<li>Telefon: <a href="tel:+01-562-867-5309">{{ . }}</a></li>{{ end }}
It's not intended to have the example telephone number hard coded in source code.

You have to find a way to manipulate `$location.phone` string to match the example scheme. Have a look at Hugo Functions https://gohugo.io/functions/

2020-10-05 09:23 UTC, midzer commented on assets/scss/_content.scss
> +}
No need to change something here.
Can you revert this one?

2020-10-05 09:23 UTC, midzer commented on assets/scss/_base.scss
> +a[href^="tel:"]:before {
This is looking good, but I have to doublecheck before merge if styling of the telephone icon fits propery.

2020-10-06 02:55 UTC, ReyhanSara commented
Hi. Thanks for pointing it out!
Appreciate if you could provide some instructions on setting this up in the local environment as I was unable to do so and the language and template is fairly new to me. In the meantime I will continue to work on the required changes where ever possible.

2020-10-06 13:39 UTC, midzer commented
@ReyhanSara Have a look at new `README.md` https://github.com/lokal-ninja/ln-base/blob/master/README.md. Feel free to ask if you have further questions. Have a nice week!

2020-10-07 06:59 UTC, ReyhanSara commented
Sure, that's great. Thank you!

2020-10-07 12:24 UTC, ReyhanSara commented on assets/scss/_content.scss
> +}
Sorry, it was a mistake.

2020-10-07 12:25 UTC, ReyhanSara commented on layouts/_default/single.html
> +        {{ with $location.phone }}<li>Telefon: <a href="tel:+01-562-867-5309">{{ . }}</a></li>{{ end }}
what does $location.phone string look like?

2020-10-07 12:36 UTC, midzer commented on layouts/_default/single.html
> +        {{ with $location.phone }}<li>Telefon: <a href="tel:+01-562-867-5309">{{ . }}</a></li>{{ end }}
It's an international number with spaces, for example `+49 421 69 69 77 67` via https://lokal.ninja/bremen/bremen/albers-maritim/

2020-10-07 13:42 UTC, ReyhanSara commented on layouts/_default/single.html
> +        {{ with $location.phone }}<li>Telefon: <a href="tel:+01-562-867-5309">{{ . }}</a></li>{{ end }}
oh alright. 

Any idea as to why I'm seeing these error?
![error](https://user-images.githubusercontent.com/40003718/95338795-ec8fd100-08d0-11eb-9e4d-8d6b7b9aea9b.JPG)

2020-10-07 14:39 UTC, midzer commented on layouts/_default/single.html
> +        {{ with $location.phone }}<li>Telefon: <a href="tel:+01-562-867-5309">{{ . }}</a></li>{{ end }}
Yes, telephone number with hyphens.

Where do you got an error?

2020-10-07 15:07 UTC, ReyhanSara commented on layouts/_default/single.html
> +        {{ with $location.phone }}<li>Telefon: <a href="tel:+01-562-867-5309">{{ . }}</a></li>{{ end }}
I installed hugo on my windows machine and followed the instructions on the ReadMe file. The errors above appear when I attempt to execute command "hugo server".

2020-10-07 15:27 UTC, ReyhanSara commented on layouts/_default/single.html
> +        {{ with $location.phone }}<li>Telefon: <a href="tel:+01-562-867-5309">{{ . }}</a></li>{{ end }}
```suggestion
      {{ with $location.phone }}<li>Telefon: <a href="tel:{{ replace $location.phone ' ' '-'}}">{{ . }}</a></li>{{ end }}
```
Meanwhile, the above line is what I have in mind with regards to the manipulation required. Let me know if this is right so that I can create a fresh PR.

2020-10-07 15:56 UTC, midzer commented on layouts/_default/single.html
> +        {{ with $location.phone }}<li>Telefon: <a href="tel:+01-562-867-5309">{{ . }}</a></li>{{ end }}
Sorry, I cannot see your errors you are getting after `hugo server`.
The `replace` is looking good. Although you can try to use `.` instead of `$location.phone` inside the function.
No need to create another PR. Just push another commit to your branch of this repo.

2020-10-07 18:22 UTC, midzer commented on assets/scss/_base.scss
> +a[href^="tel:"]:before {
Just double checked it. This is fine!

2020-10-07 18:26 UTC, midzer requested changes
Thanks for your continued work on this. Just minor changes and we're good to go :)

2020-10-07 18:26 UTC, midzer commented on layouts/_default/single.html
> +      {{ with $location.phone }}<li>Telefon: <a href="tel:{{ replace . ' ' '-'}}">{{ . }}</a></li>{{ end }}
Okay, i just had a look.

We should use https://gohugo.io/functions/urlize/ instead of `replace`.

Dont want to be pickly, but check your intendation, too. Right now it does not align with the line above and below.

2020-10-07 18:26 UTC, midzer commented on layouts/_default/single.html
> +{{- end }}
What was changed here?

2020-10-08 01:13 UTC, ReyhanSara commented on layouts/_default/single.html
> +{{- end }}
Sorry, I have no idea how that change occured. It may have been an accident on my end.

2020-10-08 01:24 UTC, ReyhanSara commented on layouts/_default/single.html
> +      {{ with $location.phone }}<li>Telefon: <a href="tel:{{ replace . ' ' '-'}}">{{ . }}</a></li>{{ end }}
Thank you for pointing out and no problem, I'm enjoying the learning process and glad to receive feedback and make improvements ! 
Kindly check out my last commit  (7ba6081), the previous commit was an accident and I'm currently figuring out how to revert it.
Do let me know if I need to make any more changes.

2020-10-15 17:56 UTC, midzer requested changes
Only a minor change request.
Please have a look.
Then we're ready for merge, i guess.

2020-10-15 17:56 UTC, midzer commented on assets/scss/_content.scss
> +}
In fact, I dont even know exactly what has been changed here. I hope it breaks nothing.

2020-10-15 17:56 UTC, midzer commented on layouts/_default/single.html
> +        {{ with $location.phone }}<li>Telefon: <a href="tel:{{ . | urlize }}">{{ . }}</a></li>{{ end }}
Does `urlize . ` work, too?

Then we are ready for merge!

2020-10-15 17:56 UTC, midzer commented on layouts/_default/single.html
> +{{- end }}
Maybe just a blank line afterwards...

2020-10-16 05:29 UTC, ReyhanSara commented on layouts/_default/single.html
> +        {{ with $location.phone }}<li>Telefon: <a href="tel:{{ . | urlize }}">{{ . }}</a></li>{{ end }}
I'm assuming we should use urlize together with safeURL, however I'm unable to visualize the output due to the problem mentioned here, https://github.com/lokal-ninja/ln-base/pull/18#discussion_r501021891 in executing the project in my local environment.

2020-10-19 14:47 UTC, ReyhanSara commented on layouts/_default/single.html
> +        {{ with $location.phone }}<li>Telefon: <a href="tel:{{ . | urlize }}">{{ . }}</a></li>{{ end }}
Appreciate if you could guide me on how to resolve the errors as shown in the image here https://github.com/lokal-ninja/ln-base/pull/18#. Once I successfully get it running on my local machine I can start working on issue #7

2020-10-19 15:26 UTC, midzer commented on layouts/_default/single.html
> +        {{ with $location.phone }}<li>Telefon: <a href="tel:{{ . | urlize }}">{{ . }}</a></li>{{ end }}
What errors are you getting? I can't see an image in your link (which points to this PR).

Did you follow setup instructions from https://github.com/lokal-ninja/ln-base/blob/master/README.md ?

2020-10-19 15:44 UTC, ReyhanSara commented on layouts/_default/single.html
> +        {{ with $location.phone }}<li>Telefon: <a href="tel:{{ . | urlize }}">{{ . }}</a></li>{{ end }}
yes I followed the instructions after installing hugo to my machine
This is  how it appears when I finally run command 'hugo server'


Sara@REYHANSARA MINGW64 /e/OS/bremen (master)
$ hugo server
Start building sites …
WARN 2020/10/19 21:09:56 .File.Dir on zero object. Wrap it in if or with: {{ with .File }}{{ .Dir }}{{ end }}
ERROR 2020/10/19 21:09:56 render of "page" failed: "E:\OS\bremen\themes\ln-base\layouts\_default\baseof.html:14:20": execute of template failed: template: _default/single.html:14:20: executing "_default/single.html" at <index .Site.Data $main $city .File.BaseFileName>: error calling index: index of nil pointer
ERROR 2020/10/19 21:09:56 render of "page" failed: "E:\OS\bremen\themes\ln-base\layouts\_default\baseof.html:14:20": execute of template failed: template: _default/single.html:14:20: executing "_default/single.html" at <index .Site.Data $main $city .File.BaseFileName>: error calling index: index of nil pointer
ERROR 2020/10/19 21:09:56 render of "page" failed: "E:\OS\bremen\themes\ln-base\layouts\_default\baseof.html:14:20": execute of template failed: template: _default/single.html:14:20: executing "_default/single.html" at <index .Site.Data $main $city .File.BaseFileName>: error calling index: index of nil pointer
ERROR 2020/10/19 21:09:56 render of "page" failed: "E:\OS\bremen\themes\ln-base\layouts\_default\baseof.html:14:20": execute of template failed: template: _default/single.html:14:20: executing "_default/single.html" at <index .Site.Data $main $city .File.BaseFileName>: error calling index: index of nil pointer
ERROR 2020/10/19 21:09:56 TOCSS: failed to transform "scss/vendor/choices.scss" (text/x-scss): resource "scss/bremen/scss/vendor/choices.scss_f300667da4f5b5f84e1a9e0702b2fdde" not found in file cache
ERROR 2020/10/19 21:09:56 TOCSS: failed to transform "scss/app.scss" (text/x-scss): resource "scss/bremen/scss/app.scss_f300667da4f5b5f84e1a9e0702b2fdde" not found in file cache
Built in 9877 ms
Error: Error building site: failed to render pages: render of "page" failed: "E:\OS\bremen\themes\ln-base\layouts\_default\baseof.html:14:20": execute of template failed: template: _default/single.html:14:20: executing "_default/single.html" at <index .Site.Data $main $city .File.BaseFileName>: error calling index: index of nil pointer

2020-10-19 15:56 UTC, midzer commented on layouts/_default/single.html
> +        {{ with $location.phone }}<li>Telefon: <a href="tel:{{ . | urlize }}">{{ . }}</a></li>{{ end }}
I realize you're using windows. Somehow paths are mixed up in your minGW, i think.

Try to build directly in Windows. There is a `hugo.exe`.
I tried a fresh setup of `README.md` under Linux and everything worked as expected.

2020-10-19 16:07 UTC, ReyhanSara commented on layouts/_default/single.html
> +        {{ with $location.phone }}<li>Telefon: <a href="tel:{{ . | urlize }}">{{ . }}</a></li>{{ end }}
Yep, I use windows. I will see to it.
Thanks!

2020-10-28 21:00 UTC, midzer approved these changes
I've checked everything and it works well. Very nice!

2020-10-28 21:01 UTC, merged

2020-10-30 09:58 UTC, ReyhanSara commented
> I've checked everything and it works well. Very nice!
I'm glad it worked. Thank you for the support and guidance!